### ISSUE TITLE
[solved] Self Test of asciidoc3api fails

### ISSUE THREAD

**Issue by tbpassin** [asciidoc3/asciidoc3#10]
Running the asciidoc3api module from the command line fails.

System:
    Windows 10
    Python 3.8
    pip install
    not a virtual environment

Many of the self-tests failed.  The key part of typical error messages was -
```
    Traceback (most recent call last):
      File "C:\Users\tom\AppData\Roaming\Python\Python38\site-packages\asciidoc3\asciidoc3api.py", line 229, in execute
        self.asciidoc3.execute(self.cmd, opts.values, args)
    AttributeError: module 'asciidoc3' has no attribute 'execute'
```
There were also error messages that included a similar problem -
```
self.messages = self.asciidoc3.messages[:]
    AttributeError: module 'asciidoc3' has no attribute 'messages'
```
The reason is that the import of ``asciidoc3`` caused it to be the asciidoc3 *package*, not the asciidoc3.py *module*.  I was able to correct both problems by the following code (original code commented out) -

```
        self.__import_asciidoc3(reload=True)
        try:
            try:
                from asciidoc3 import asciidoc3 as _asciidoc3
                _asciidoc3.execute(self.cmd, opts.values, args)
                #self.asciidoc3.execute(self.cmd, opts.values, args)
            finally:
                self.messages = _asciidoc3.messages[:]
                #self.messages = self.asciidoc3.messages[:]
        except SystemExit as e:
            if e.code:
                raise AsciiDoc3Error(self.messages[-1])
```
After these changes, the self test completed without errors, except for two that complained about some kind of format or syntax error in the text - not an issue with the asciidoc3api code itself.

I was also able to transform a file within a python program using the ``execute(infile, outfile, backend='html5')`` method.  Previously this had failed.

**Comment by asciidoc3** [comment]
Hi tbpassin,
the original code works well on GNU/Linux and in Windows venv.
But I can reproduce the issue you reported, too.
Thanks for your suggestion, give me a few days for testing.

**Comment by tbpassin** [comment]
Maybe adding a conditional import would cover all the bases:

       self.__import_asciidoc3(reload=True)
       try:
            from asciidoc3 import asciidoc3 as _asciidoc3
       except ImportError:
             _asciidoc3 =self.asciidoc3           
       try:
            try:
                _asciidoc3.execute(self.cmd, opts.values, args)
                #self.asciidoc3.execute(self.cmd, opts.values, args)

**Comment by asciidoc3** [comment]
Unfortunately none of your suggestions work with GNU/Linux:
`AttributeError: 'function' object has no attribute 'execute'`
I tried some variations, too :-) So this problem seems to occur only when using pip on Windows (?!) ... Needs more time to be localised.

**Comment by tbpassin** [comment]
On my Windows 10 system -
```
>>> from asciidoc3 import asciidoc3
>>> type(asciidoc3)
<class 'module'>
>>> type(asciidoc3.execute)
<class 'function'>
```

Maybe this could be used to decide which form to use after the try/except.  Or set a flag to indicate whether the ``try`` or the ``except`` branch was used.

**Comment by asciidoc3** [comment]
closed
