### ISSUE TITLE
[solved] Post-install Fails on Windows (and a fix)

### ISSUE THREAD

**Issue by tbpassin** [asciidoc3/asciidoc3#9]
I tried to install asciidoc3 on Windows and the post-install failed.  I did everything suggested in the install doc (this is not in a virtual environment) plus some other things, and nothing succeeded.

The problem is that I have both Python2 and Python3 installed on my computer.  The post-install step tries to run "pip show asciidoc3", but on my system "pip" runs the python2 version of pip, not python3.  I would have to run pip3 to get python3 and its site-packages directory.  Instead of trying to symlink pip to pip3, I edited the post-install file to run "python3 -m pip show asciidoc3" instead of "pip show asciidoc3".  This succeeded.

However, there is a better way, and also a simpler way to find ad3_location.  Here's what I suggest - in the post-install python file:
```
import site
ad3_location = site.getusersitepackages() # e.g., C:\Users\tom\AppData\Roaming\Python\Python38\site-packages
```
I'm upgrading a Leo-editor plugin to be able to render asciidoc (it already renders RsT and md), so I would really appreciate it if this change could be made.  Otherwise the Windows install may be tricky for users.

**Comment by tbpassin** [comment]
If for some reason related to symlinks and file locations on Linux the above doesn't quite do it, it would be better to run pip with ``sys.executable -m pip``  than the way it's currently being done.  Then the correct version of pip would automatically be run, no symlinking required.

And in fact, on some linux systems, "python" will still launch python 2.x.  One needs to run "python3" if that's what you want.  So this problem may not exist only on Windows.

**Comment by asciidoc3** [comment]
Hi tbpassin,
the coexistence of Python2 and Python3 was one of the biggest hurdles when porting AsciiDoc to AsciiDoc3, believe me.
GNU/Linux is a little easier to handle, because (almost) every system is automatically installed with 'python3' as an alias (or symlink)  to the current Python3 version.

I did hope that the Python2 EOL would 'solve' this confusion synchronously, but this seems not to work (so far). The situation on Windows is even worse, think about 'py -3' and so on. Sooner or later I'd like to go back to a simple 'python' when the program has to call the executable.

In the meantime I appreciate your suggestion 

```
import site
ad3_location = site.getusersitepackages()
sys.executable -m pip
```

Give me a few days for testing, I'll be back.

**Comment by tbpassin** [comment]
"the coexistence of Python2 and Python3 was one of the biggest hurdles when porting AsciiDoc to AsciiDoc3, believe me."

Oh, yes indeed.  Actually, on Windows I don't know why there has to be any symlinking at all.  Everything should work directly out of ``site-packages\asciidoc3``.  I think I understand why you needed that machinery on Linux - I read the thread on making it work under the Debian packaging conventions - but I don't think there would be any issues like that on Windows.  Of course, the packaging would have to be changed a little.  My Windows ``pip`` installation didn't work until I patched the post install to run.  But I don't see why it couldn't be made to work with no post install step without much effort.  The setup program would need to be mildly changed.  The post-install program would have to be correspondingly changed, and that might be harder, I don't have an opinion because I don't know what's involved.

Anyway, I do recommend using ``sys.executable -m`` everywhere.  That way you are guaranteed to get the right version, as long as the user is running the right python version in the first place.

Thanks for taking a look at this so quickly.

**Comment by asciidoc3** [comment]
Hi,
to make it as simple as possible and to provide a quick 'workaround' I'll change two lines:
(in 'asciidoc3_postinstall.py', original code commented out)

```
        ...
        py3_exe = sys.executable
        runpip = subprocess.Popen(py3_exe + " -m pip show asciidoc3", shell=True,
        # runpip = subprocess.Popen("pip show asciidoc3", shell=True,       
        ...

```
This should prevent 'subprocess' from using (Python2-) pip. Using 'import site' is a possible way to ease the pain of locating the packages installed by pip. Probably this will be used within a forthcoming general update.
In the meantime the above change will be found on PyPI: AsciiDoc3 3.2.0 -> 3.2.1

**Comment by tbpassin** [comment]
If ``site`` is used, remember that there can be more than one location - e.g., a global and a local user location.  ``site.getsitepackages()`` returns a list of them.

**Comment by asciidoc3** [comment]
closed
